"""initial schema

Revision ID: ade2084af9cd
Revises: 
Create Date: 2026-03-19 18:24:32.460504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ade2084af9cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archaeological_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('quranic_name', sa.String(length=200), nullable=True),
    sa.Column('surah_refs', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('modern_location', sa.String(length=300), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archaeological_refs', sa.Text(), nullable=True),
    sa.Column('geojson', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chemical_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_source', sa.String(length=200), nullable=False),
    sa.Column('element', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('analytical_method', sa.String(length=200), nullable=True),
    sa.Column('sample_location', sa.String(length=300), nullable=True),
    sa.Column('publication_doi', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hydro_monitoring',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('station', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=100), nullable=False),
    sa.Column('sample_label', sa.String(length=200), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=True),
    sa.Column('collection_location', sa.String(length=300), nullable=True),
    sa.Column('element', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('analytical_method', sa.String(length=200), nullable=True),
    sa.Column('lab_name', sa.String(length=300), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('certificate_path', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('journal', sa.String(length=300), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=200), nullable=True),
    sa.Column('pmid', sa.String(length=20), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi'),
    sa.UniqueConstraint('pmid')
    )
    op.create_table('satellite_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite', sa.String(length=50), nullable=False),
    sa.Column('band', sa.String(length=50), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('resolution_m', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('bbox_wkt', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('satellite_data')
    op.drop_table('publications')
    op.drop_table('lab_samples')
    op.drop_table('hydro_monitoring')
    op.drop_table('chemical_analyses')
    op.drop_table('archaeological_sites')
    # ### end Alembic commands ###
